### ISSUE TITLE
선택한 메뉴수에 따른 로직 추가

### ISSUE THREAD

**Issue by ppplll87** [zzinpan/menu#1]
[AS-IS]
1주에 5일 & 5개의 메뉴 선택했을때 랜덤으로 중복없이 메뉴선정됨

[ISSUE]
메뉴를 5개 이상 선택하지 않을경우 메뉴가 선정되지 않은 빈 날짜 발생

[TO-BE]
메뉴를 꼭 5개 선택하지 않아도 빈칸없이 메뉴 선정되도록 변경
(ex) 5개 이하의 메뉴를 선택했을때는 중복을 포함하여 5일 전체 메뉴가 선정되도록
5개 이상의 메뉴를 선택했을때는 중복없이 5일 전체 메뉴가 선정되도록

**Comment by zzinpan** [comment]
요구 [TO-BE] 적용 완료.

**Comment by ppplll87** [comment]
GOOD!!!!! @zzinpan
